// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ7bQeDXGfshXckrOPJyUF0Knbo7GPLL4',
    appId: '1:520920693154:android:abab33160f2553b99c5afb',
    messagingSenderId: '520920693154',
    projectId: 'moco-5bda4',
    storageBucket: 'moco-5bda4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzXQAM1zqZqTJVADDFuT5bbYJ1Rja0LBQ',
    appId: '1:520920693154:ios:d2f8c5dbb6880dcb9c5afb',
    messagingSenderId: '520920693154',
    projectId: 'moco-5bda4',
    storageBucket: 'moco-5bda4.firebasestorage.app',
    iosBundleId: 'com.moco.moneycontrol',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABDsaN8DgdULZDaqpCy4ljlncXv79fbh0',
    appId: '1:520920693154:web:313a8592058c80359c5afb',
    messagingSenderId: '520920693154',
    projectId: 'moco-5bda4',
    authDomain: 'moco-5bda4.firebaseapp.com',
    storageBucket: 'moco-5bda4.firebasestorage.app',
    measurementId: 'G-DCW9N7M6W2',
  );

}